name: toeic

services:
  frontend:
    restart: unless-stopped
    networks:
      - app

  backend:
    restart: unless-stopped
    expose:
      - "5000"
    networks:
      app:
        aliases:
          - backend-app

  nginx:
    image: nginx:1.27-alpine
    restart: unless-stopped
    networks:
      - app

  mysql:
    image: mysql:8.4
    restart: unless-stopped
    networks:
      - app

networks:
  app:
    driver: bridge

volumes:
  mysql_data: